# Generated by Django 3.2.5 on 2021-11-14 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('bibliography_source', models.CharField(max_length=5000)),
                ('bibliography_title', models.CharField(max_length=500)),
                ('bibliography_type', models.CharField(choices=[('RA', 'Research Article'), ('WA', 'Web Article'), ('AV', 'Audio Video')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('bibliography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bibliography')),
            ],
        ),
    ]
