# Generated by Django 3.2.5 on 2021-11-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
