# Generated by Django 3.2.5 on 2021-11-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_bibliography_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='bibliography_source',
            field=models.TextField(max_length=5000),
        ),
    ]
